name: Workshop Deploy
description: "Allows you to deploy a workshop with an amp"
author: "Evan Cole"
date: "2025-08-15"
specification_version: "1.0"
prototype_version: "1.0"

# 1) Ask the user for a value when launching the AMP
environment_variables:
  NUM_USERS:
    default: "5"
    description: "How many users are doing the workshop?"
    required: true
    
   TEAM_NAME:
    default: "AgentLabGroup"
    description: "Name of of the CAI team with acesss permssions to the projects"
    required: true

# (Optional) recommend a runtime
runtimes:
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard

tasks:
  # 2) Create jobs
  - type: create_job
    name: Provision
    entity_label: provision_job       
    script: provision.py
    kernel: python3
    cpu: 1
    memory: 2

  - type: create_job
    name: Permission
    entity_label: permission_job
    script: permission.py
    kernel: python3
    cpu: 1
    memory: 2
    
   - type: create_job
    name: Teardown
    entity_label: teardown_job
    script: teardown.py
    kernel: python3
    cpu: 1
    memory: 2
    short_summary: "Create a teardown job"

  # 3) Run them in order (permission after provision)
  - type: run_job
    entity_label: provision_job
    short_summary: "Run provision"

  - type: run_job
    entity_label: permission_job
    short_summary: "Run permission"