---
environment_variables:
  NUM_USERS:
    default: "5"
    description: How many users are doing the workshop?
    required: true
  TEAM_NAME:
    default: AgentLabGroup
    description: Name of the CAI team with access permissions to the projects
    required: true
runtimes:
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard
tasks:
  - type: create_job
    name: Provision
    entity_label: provision_job
    script: provision.py
    kernel: python3
    cpu: 1
    memory: 2
    short_summary: Create a provision job
  - type: create_job
    name: Permission
    entity_label: permission_job
    script: permission.py
    kernel: python3
    cpu: 1
    memory: 2
    short_summary: Create a permission job
  - type: create_job
    name: Teardown
    entity_label: teardown_job
    script: teardown.py
    kernel: python3
    cpu: 1
    memory: 2
    short_summary: Create a teardown job
  - type: run_job
    entity_label: provision_job
    short_summary: Run provision
  - type: run_job
    entity_label: permission_job
    short_summary: Run permission

